version: '2'
services:
    generic-app:
        image: generic
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://generic-mysql:3306/generic?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9090:9090
    generic-mysql:
        extends:
            file: mysql.yml
            service: generic-mysql
